# Generated by Django 6.0.1 on 2026-04-05 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated skills')),
                ('role', models.CharField(choices=[('field_worker', 'Field Worker'), ('medical_volunteer', 'Medical Volunteer'), ('teaching_volunteer', 'Teaching Volunteer'), ('coordinator', 'Coordinator'), ('fundraiser', 'Fundraiser'), ('other', 'Other')], max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave')], default='active', max_length=20)),
                ('joining_date', models.DateField()),
                ('assigned_tasks', models.TextField(blank=True, help_text='Current assigned tasks')),
                ('availability', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('weekends', 'Weekends'), ('on_call', 'On Call')], default='part_time', max_length=20)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='volunteers/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'Leave')], max_length=10)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='volunteers.volunteer')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('volunteer', 'date')},
            },
        ),
    ]
