# Generated by Django 6.0.1 on 2026-05-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_award_statistic_teammember_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='section',
            field=models.CharField(choices=[('about', 'About Us'), ('mission', 'Our Mission'), ('vision', 'Our Vision'), ('values', 'Core Values'), ('history', 'Our History'), ('founder_message', "Founder's Message"), ('ceo_message', "CEO's Message")], max_length=20, unique=True),
        ),
    ]
