# Generated by Django 6.0.1 on 2026-04-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly base salary', max_digits=10),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='supervisor',
            field=models.CharField(blank=True, help_text='Name of supervisor', max_length=200),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('admin_staff', 'Admin Staff'), ('coordinator', 'Coordinator'), ('accountant', 'Accountant'), ('guard', 'Security Guard'), ('other', 'Other')], max_length=20),
        ),
    ]
