# Generated by Django 6.0.1 on 2026-04-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=200)),
                ('donor_contact', models.CharField(blank=True, max_length=50)),
                ('donor_email', models.EmailField(blank=True, max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('general', 'General'), ('zakat', 'Zakat'), ('sadqa', 'Sadqa'), ('fitrana', 'Fitrana'), ('education', 'Education'), ('healthcare', 'Healthcare'), ('other', 'Other')], default='general', max_length=20)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('online', 'Online')], default='cash', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('salaries', 'Salaries'), ('rent', 'Rent'), ('utilities', 'Utilities'), ('transport', 'Transport'), ('medical', 'Medical'), ('education', 'Education'), ('food', 'Food'), ('maintenance', 'Maintenance'), ('office', 'Office Supplies'), ('other', 'Other')], default='other', max_length=20)),
                ('paid_to', models.CharField(blank=True, max_length=200)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('online', 'Online')], default='cash', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('approved_by', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
