# Generated by Django 6.0.1 on 2026-04-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_modules',
            field=models.CharField(blank=True, help_text='Comma-separated module names for limited admin (e.g. students,volunteers,daily_expenses)', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Main Administrator'), ('limited_admin', 'Limited Administrator'), ('staff', 'Staff Member'), ('volunteer', 'Volunteer')], default='staff', max_length=20),
        ),
    ]
